config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/browse" => "browse#browse", as: :browse
  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise, if: :devise_controller?

  private
    def configure_devise
      devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :username, images: [] ])
    end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def browse
    @users = Account.where.not(id: current_account.id)
  end

  def approve
    # right swipe
  end

  def decline
    # left swipe
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/browse/browse.html.erb
<ul id="slides">
  <% @users.each_with_index do |user, i| %>
  <li class="slide <%= 'showing' if i == 0 %>" data-id="<%= user.id %>">
    <div class="image-carousel" style="background-image: url('<%= url_for user.images.first %>')">
    </div>
    <span class="user-details">
      <span class="user-name"><%= user.first_name %></span>, 31<br />
      <i class="fa fa-graduation-cap mr-2"></i> Physician<br>
      <i class="fa fa-map-marker mr-3"></i> Dallas
    </span>
  </li>
  <% end %>
</ul>

<div id="slide-controls">
  <span id="decline"><i class="fa fa-times-circle fa-2x" style="color: #555; margin-right: 5px;"></i></span>
  <span id="approve"><i class="fa fa-heart fa-2x" style="color: red; margin-left: 5px;"></i></span>
</div>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">© 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">TinderLike</h5>

  <% if account_signed_in? %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to 'Browse', browse_path, class: "text-dark mr-3" %>
      <%= link_to 'My Matches', "#", class: "text-dark mr-3" %>
      <%= link_to 'Settings', edit_account_registration_path, class: "text-dark" %>
    </nav>
    <%= link_to 'Sign out', destroy_account_session_path, method: :delete, class: "btn btn-outline-primary" %>
  <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#">Features</a>
      <a class="p-2 text-dark" href="#">Support</a>
      <a class="p-2 text-dark" href="#">Pricing</a>

      <%= link_to 'Sign in', new_account_session_path, class: "btn btn-secondary mr-2" %>
      <%= link_to 'Sign up', new_account_registration_path, class: "btn btn-outline-primary" %>
  </nav>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinderlike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>


    <div class="container">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>